import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../../styles/Home.module.css'
import Script from 'next/script'


export default function Home() {
  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className={styles.flex_a}>Перед использованием, нужен доступ</p>
      <a className={styles.flex_a} href='https://drive.google.com/file/d/18FcnHJzaiZutscGQcX_zIR_cpaMJJJh5/view?usp=sharing'>Лаба №3</a>

    </>
  )
}
