import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from "react";
import emailjs from 'emailjs-com';

export default function ContactUs() {
  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
      </Head>

      <h1 className={styles.flexcontainer}>Расписание на неделю:</h1>
    </>
  )
} 