import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from "react";
import Image from 'next/image';
import zacon from '../public/Закон кулона.jpg'

export default function TEST() {

  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
      </Head>
      
      <header className={styles.header}>
          <div>
              <a href="https://urtt.ru" className={styles.logo}>УРТК.ру</a>
              <div className={styles.headerr}>
                  <a href="../">Главная</a>
                  <a href="../posts">Лабы по Кс</a>
                  <a href="../about/about">Тфу-пдф</a>
                  <a href="../ter ">Тер-Вер</a>
                  <a href="../test">Тест</a>
              </div>
          </div>
      </header>

      <h1 className={styles.flex_text}>Тут будут ответы на экзамен</h1>

      <p>Вопросы:</p>
      <p>1)Электрическое поле. Напряженность электрического поля - это векторная физическая величина, характеризующая электрическое поле в данной точке и равная отношению силы F →, действующей на неподвижный малый по величине точечный заряд, помещённый в данную точку, к величине этого заряда q*</p>
      <div className={styles.imag}>
        <Image
        src={zacon}
        width={300}
        height={60}
        alt="Picture of the author"
        />
      </div>

    </>
  )
}


