import Head from 'next/head'
import Image from 'next/image'
import { Headland_One, Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import React from "react";

export default function TEST() {

    function functionName() {
      write("You are learning how to call JavaScript function in html");
    }

    const [likes, setLikes] = React.useState(0);

    function handleClick(e) {
        setLikes(likes + 1);
        e.preventDefault();
      console.log('Была нажата ссылка.');
    }

    function handleClick2(e) {
      setLikes(likes - 1);
      e.preventDefault();
      console.log('Была нажата ссылка.');
    }


    const today = new Date();

  function formatDate(date) {
    return new Intl.DateTimeFormat(
      'ru-RU',
      { weekday: 'long' }
    ).format(date);
  }

    function Click(e) {
      e.preventDefault();
      console.log('Была нажата ссылка.');
    }   

  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
      </Head>
      
     

      <header className={styles.header}>
          <div>
              <a href="https://urtt.ru" className={styles.logo}>УРТК.ру</a>
              <div className={styles.headerr}>
                  <a href="../">Главная</a>
                  <a href="../posts">Лабы по Кс</a>
                  <a href="../about/about">Тфу-пдф</a>
                  <a href="../ter ">Тер-Вер</a>
                  <a href="../test">Тест</a>
              </div>
          </div>
      </header>
    

    <h1>Список дел на {formatDate(today)}</h1>

    <input type = "button" onClick = {functionName} value = "Click Me"/>

    <button onClick={handleClick}>Like ({likes})</button>
    <button onClick={handleClick2}>Like ({likes})</button>

    <h1>Тестовая версия, всего что будет на сайте</h1>

    <a href="#" onClick={Click}>
      Нажми на меня
    </a>

    <div id='root'></div>

    </>
  )
}


